/**
 * @fileoverview gRPC-Web generated client stub for ingredient
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.14.0
// source: proto/ingredient.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.ingredient = require('./ingredient_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ingredient.IngredientServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ingredient.IngredientServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ingredient.IngredientRequest,
 *   !proto.ingredient.IngredientReply>}
 */
const methodDescriptor_IngredientService_AddIngredient = new grpc.web.MethodDescriptor(
  '/ingredient.IngredientService/AddIngredient',
  grpc.web.MethodType.UNARY,
  proto.ingredient.IngredientRequest,
  proto.ingredient.IngredientReply,
  /**
   * @param {!proto.ingredient.IngredientRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ingredient.IngredientReply.deserializeBinary
);


/**
 * @param {!proto.ingredient.IngredientRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ingredient.IngredientReply)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ingredient.IngredientReply>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ingredient.IngredientServiceClient.prototype.addIngredient =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ingredient.IngredientService/AddIngredient',
      request,
      metadata || {},
      methodDescriptor_IngredientService_AddIngredient,
      callback);
};


/**
 * @param {!proto.ingredient.IngredientRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ingredient.IngredientReply>}
 *     Promise that resolves to the response
 */
proto.ingredient.IngredientServicePromiseClient.prototype.addIngredient =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ingredient.IngredientService/AddIngredient',
      request,
      metadata || {},
      methodDescriptor_IngredientService_AddIngredient);
};


module.exports = proto.ingredient;

